updated clevertap-web-sdk and clevertap ts version.
Leanplum/Leanplum-JavaScript-SDK pull request #184
Opened 2024-09-11 09:04 UTC by KambleSonam

- Updated clevertap-web-sdk version
- Updated clevertap-ts version
- Added regions 
- Updated clevertap init statement

2024-09-11 12:47 UTC, iignatov requested changes

2024-09-11 12:47 UTC, iignatov commented on package-lock.json
We're using `yarn`, the changes should be made only to `yarn.lock` and this file (`package-lock.json`) shouldn't be committed.

2024-09-11 13:39 UTC, KambleSonam commented on package-lock.json
Got it @iignatov . Changes are done.

2024-09-12 07:45 UTC, iignatov approved these changes

2024-09-13 07:31 UTC, merged

2024-09-13 10:43 UTC, iignatov commented
:tada: This PR is included in version 1.13.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/leanplum-sdk/v/1.13.0)
- [GitHub release](https://github.com/Leanplum/Leanplum-JavaScript-SDK/releases/tag/1.13.0)
- `1.13.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: